version : '2'

volumes:
  nextcloud:
  nextcloud_mysql:
  
services:
  nextcloud_mysql:
    image: mysql:latest
    container_name: nextcloud_mysql
    volumes:
      - nextcloud_mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  nextcloud_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nextcloud_pma
    links:
      - nextcloud_mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
      
  nextcloud:
    image: nextcloud:latest
    volumes:
      - nextcloud:/var/www/html/
    ports:
      - 8080:80
    links:
      - nextcloud_mysql
    restart: always
